import type { Metadata } from "next";
import localFont from "next/font/local";
import AppProvider from "@/Components/AppProvider";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Calculator",
  description: "Generated by Mahid Khoramjoo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-blue-300 h-screen w-screen overflow-hidden`}
        cz-shortcut-listen='true'>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
